name: Kink Radio Playlist Scraper

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Manual trigger

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set timezone to Europe/Amsterdam
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Amsterdam

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Cache scraper dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/scraper
          key: ${{ runner.os }}-scraper-${{ hashFiles('**/requirements.txt', 'scrape_playlist.py') }}
          restore-keys: |
            ${{ runner.os }}-scraper-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create cache directory
        run: mkdir -p ~/.cache/scraper

      - name: Run playlist scraper
        id: scraper
        run: |
          python scrape_playlist.py \
            --cache-dir ~/.cache/scraper \
            --max-age 300  # 5-minute cache tolerance

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [[ -n "$(git status --porcelain docs/playlist.json)" ]]; then
            git add docs/playlist.json
            git commit -m "Update playlist data"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}